version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: myai-docker.pkg.coding.net/devops/gocode/gocode-docker:latest
    container_name: mygit
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8088:3000"
      - "2221:22"